### PR TITLE
Fixing failed vignette build

### PR DESCRIPTION
**Pull request by Max-Bladen**
SOURCE:
https://github.com/mixOmicsTeam/mixOmics/issues/169

### CODE REVIEW

**Comment by Max-Bladen** [comment]
Unable to reproduce this issue in a local `R` or `Rmd` file. 

Thought issue was exclusive to `plotLoadings()`, but even when all chunks with this function are set to `eval = FALSE`, GitHub action fails at different point in the code. 

Searching for `length(class2)` within all files yields nothing, so it is likely an issue caused by a function within one of the packages `mixOmics` is dependent on.

Might need your help on this one @aljabadi

**Comment by Max-Bladen** [comment]
Even when all code chunks are set to `eval = FALSE` within `vignette.Rmd`, the checks still fail. It is drawn from different functions, but the error that is raised is the same.

**Comment by aljabadi** [comment]
@Max-Bladen let's see if https://github.com/mixOmicsTeam/mixOmics/pull/174 is successful. If so, we'll use the stable version of R and Bioc until the dust settles.

**Comment by aljabadi** [comment]
@Max-Bladen build is now fine with stable versions. We can safely ignore these changes :)

**Pull request closed without merging**
