### PR TITLE
Return the value of the user's parameters

### PR DESCRIPTION
**Pull request by abodein**
Hello, 
I'm working on a package related to mixOmics. It would be good to return the value of the user's parameters in addition to the function call. Here are my suggestions.
Thank you in advance.

### CODE REVIEW

**Comment by aljabadi** [comment]
Hi @abodein.,
Thanks for the suggestion. The call is in fact already returned in the `$call` entry of the `pca` object (see example below). Same goes for all core functions.
```
suppressMessages(library(mixOmics))

data(multidrug)
pca.res <- pca(X=multidrug$ABC.trans, ncomp = 4, scale = TRUE, max.iter = 999)

pca.res$call
#> pca(X = multidrug$ABC.trans, ncomp = 4, scale = TRUE, max.iter = 999)
```

Please let us know if you have any further questions/suggestions while working on your project!

**Comment by abodein** [comment]
Hi,
That is true but the value are not returned.
For example if the user use a custom variable, the name of the variable is
returned but not the value.

```{r}
suppressMessages(library(mixOmics))

data(multidrug)

my_comp <- 4

pca.res <- pca(X=multidrug$ABC.trans, ncomp = my_comp, scale = TRUE,
max.iter = 999)

pca.res$call$ncomp
#> my_comp
```

With this example, how can I get the value of `my_comp` ?

Thank you in advance for your answer.

**Comment by aljabadi** [comment]
Nice suggestion. I implemented what you wanted in [pca](https://github.com/mixOmicsTeam/mixOmics/blob/devel/R/pca.R#L179-L181) in the `devel` version which you can install using:
```
devtools::install_github("mixOmicsTeam/mixOmics", ref="devel")
```
Let me know if it works as you expect as it does on my end:

```
suppressMessages(library(mixOmics))
data(multidrug)
## use objects as input
my_comp <- 4
pca.res <- pca(multidrug$ABC.trans, ncomp = my_comp)
## see if ncomp is evaluated in the output call
pca.res$call$ncomp
#> [1] 4
```

We're making some changes in mixOmics and I'll implement it in other core function which developers might want to adopt as well. In the meantime, don't hesitate to let me know if you need such behaviour in other specific functions too.

**Comment by abodein** [comment]
It's working well. Thanks.
I am currently using `pca()`, `spca()`, `pls()`, `spls()`, `block.pls()` and `block.spls()`.
It would be nice to embed this feature in these specific functions and also in all the core functions of mixOmics.
Many thanks!

**Comment by aljabadi** [comment]
I added the feature to all the functions you mentioned, please re-install the latest devel version.

**Comment by aljabadi** [comment]
Hi @abodein ,

As this might affect memory usage for big datasets we will need to carefully craft this. That is why I isolated and moved this feature to a separate branch for now to better shape it before implementing in the stable version. Until then, you can install it using:
```
devtools::install_github("mixOmicsTeam/mixOmics", ref="return-full-call")
```

Although your last installation does include the feature.

**Comment by abodein** [comment]
Thanks !

**Comment by abodein** [comment]
Hi @ajabadi,
I have the following error with the new implementation.
```
X <- matrix(sample(1:1000), nrow = 10)
Y <- matrix(sample(1:100), nrow = 10)
Z <- matrix(sample(1:500), nrow = 10)

mixOmics::block.pls(X = list("X" = X, "Y" = Y, "Z" = Z), indY = 1,
                    ncomp = 5, mode = "canonical")
# Error in eval(expr, p) : argument "Y" is missing, with no default
```
It was working without the line ` cl[-1] <- lapply(cl[-1], eval.parent)`
Should we use `eval()` instead of `eval.parent()` ?

**Comment by aljabadi** [comment]
You're completely right, I just fixed it and you can re-install now. Thanks!

**Comment by abodein** [comment]
Hi @ajabadi, 

I have another problem with the argument return evaluation.
When it is wrapped inside a function, it cannot find the arguments.
Here is an example:

```
data(liver.toxicity)
data <- as.matrix(liver.toxicity$gene[1:10, 1:100])

fun <- function(ncomp) {
    spca(X = data, ncomp = ncomp)
}
fun(2)
```
Give the following error: `Error in FUN(X[[i]], ...) : object 'ncomp' not found `
Hope you can solve it. 
Thanks in advance!

**Comment by aljabadi** [comment]
Hi @abodein,

I think I took care of that in https://github.com/mixOmicsTeam/mixOmics/commit/747c639e2177b8caf1e4bde09932eef09878f676.
Please re-install from the branch and let me know if you have further issues.

**Comment by aljabadi** [comment]
Hi @Max-Bladen, I remember back when I implemented the branch mentioned above, I went through multiple iterations and came down to the implemented procedure for evaluating and appending the call object. Can you please review changes in [this commit](https://github.com/mixOmicsTeam/mixOmics/commit/747c639e2177b8caf1e4bde09932eef09878f676), compare with the implementation in [this PR](https://github.com/mixOmicsTeam/mixOmics/pull/200) and summarise your findings.

Thanks

**Comment by Max-Bladen** [comment]
Here is my brief summary @aljabadi. 

The two methods implemented are very similar. There are three primary differences between them however:

1. Your implementation undergoes this process automatically. The full call will be returned every time one of these functions is called. In cases where there are large dataframes being passed into the function, the return object will always contain the full set of data provided to the function. For users on lower end machines, the larger amount of memory taken up when not necessarily desired may be of negative consequence.
2. The PR I created implements this feature into a wider range of functions, including all `mint` variants, `plsda` variants and `rcc`
3. The type of the resulting call objects differs. I utilised a `list` object whereas you utilised a `call` object.  This seemingly only affects the downstream way this object can be used: mine can be directly passed to `do.call()` while yours can be directly passed to `eval()`. I don't think this difference is of major importance.

Primarily for reason 1 above, I think my PR would be slightly more desirable. However, I am happy to adjust it in whatever way you like. For instance, if you selected to return the `call` object rather than a `list`, I can easily implement this change to my PR.

**Pull request closed without merging**
